apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
data:
  # These values are base64 encoded
  # In a real scenario, you would use actual encoded values
  # echo -n "your-value" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGIuZXhhbXBsZS5jb206NTQzMi90YXNrcw==
  API_KEY: c2stdGVzdF9hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Ng==
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RzaWduaW5na2V5ZG9ub3RzaGFyZQ==
